<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<div class="cartall">
<div data-block="minicart" class="minicart-wrapper">
    <a class="showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
       <img src="<?php echo $this->getViewFileUrl('images/bagdot.png'); ?>" id="cart">

        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter1 qty empty">
<?php $helper = $this->helper('\Magento\Checkout\Helper\Cart');
    echo $helper->getItemsCount(); ?>
        </span>
        <?php


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
     
    // retrieve quote items collection
    $itemsCollection = $cart->getQuote()->getItemsCollection();
     
    // get array of all items what can be display directly
    $itemsVisible = $cart->getQuote()->getAllVisibleItems();
     
    // retrieve quote items array
    $items = $cart->getQuote()->getAllItems();

    $subTotal = $cart->getQuote()->getSubtotal();
    $grandTotal = $cart->getQuote()->getGrandTotal();
?>
    <div class="subtotal_cart">
        <?php echo "$".number_format($grandTotal, 2, '.', ''); ?>
        <div class="downarrow"></div>
    </div>
    </a>

    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
