<ul class="links_header">
    <li class="my_account" data-label="or">
        <a href="<?php echo $this->getUrl('customer/account') ?>"><?= $block->escapeHtml(__('My Account')) ?></a>
    </li>
    <li><a href="<?php echo $this->getUrl('wishlist') ?>"><?= $block->escapeHtml(__('Wish list'))  ?></a></li>
    <li> </li>

    <li><a href="<?php echo $this->getUrl('wishlist') ?>"><?= $block->escapeHtml(__('Shopping Cart')) ?></a></li>
    <li><a href="<?php echo $this->getUrl('wishlist') ?>"><?= $block->escapeHtml(__('Checkout')) ?></a></li>

</ul>
